version: "3.8"

services:
  mongo:
    image: mongo:latest
    ports:
      - "27018:27017"
    networks:
      - backend_network
    volumes:
      - mongo_data:/data/db
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - backend_network
      - frontend_network

  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    networks:
      - backend_network
      - frontend_network

networks:
  backend_network:
  frontend_network:

volumes:
  mongo_data:
